language: generic
sudo: required
services:
  - docker

# Create a dev/test build from separate Dockerfile.dev if available
#before_install:
#  - docker build -t vladmoldovan/guestbook-test -f Dockerfile.dev .

# Test the above build with whatever scripts
#script:
#  - docker run vladmoldovan/guestbook-test my test script command

# is test are successfull with Dev images we process with building PROD images
# which will also be uploaded to a docker repo of my choice
after_success:
  - docker build -t vladmoldovan/guestbook .
  - docker build -t vladmoldovan/guestbook_nginx ./nginx
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push vladmoldovan/guestbook
  - docker push vladmoldovan/guestbook_nginx

# Deploy; Forward the code to AWSElasticBeanstalk. 
# File Dockerrun.aws.json will be the main "docker-compose" equivalent for AWSElasticBeanstalk
deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: test_guestbook
  env: TestGuestbook-env
  bucket_name: elasticbeanstalk-eu-west-1-935292067375
  bucket-path: guestbook
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY