version: '3'
services:
  guestbook:
    build: .
    volumes:
      - ./:/code
    environment:
      REDIS_HOST: redis
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: password1
      MYSQL_DATABASE_DB: website
      MYSQL_DATABASE_HOST: mysql
  redis:
    image: "redis:alpine"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: website
      MYSQL_ROOT_PASSWORD: password1
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
